name: Build Release

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '21.6.1'
            
            - name: Install dependencies
              run: yarn install
            
            - name: Build
              run: yarn build
            
            - name: Archive production artifacts
              uses: actions/upload-artifact@v2
              with:
                name: dist
                path: dist/
            
            - name: Setup SSH Key
              uses: webfactory/ssh-agent@v0.5.3
              with:
                ssh-private-key: ${{ secrets.SSH_GITHUB_ACTION }}
            
            - name: Deploy
              run: |
                scp -r dist/* ${{ secrets.TARGET_SERVER }}:/testIndex
              env:
                SSH_PRIVATE_KEY: ${{ secrets.SSH_GITHUB_ACTION }}

            
