name: Build Release

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '21.6.1'
            
            - name: Install dependencies
              run: yarn install
            
            - name: Build
              run: yarn build
            
            - name: Archive production artifacts
              uses: actions/upload-artifact@v2
              with:
                name: dist
                path: dist/
                
            - name: Deploy
              uses: SamKirkland/FTP-Deploy-Action@4.3.0
              with:
                server: ${{ secrets.FTP_HOST }}
                username: ${{ secrets.FTP_USER }}
                password: ${{ secrets.FTP_PWD }}
                port: ${{ secrets.FTP_PORT }}
                local-dir: dist/
                server-dir: ${{ secrets.FTP_DIR }}/index/


